### ISSUE TITLE
Unable to access archive

### ISSUE THREAD

**Issue by mcbuch** [ecederstrand/exchangelib#348]
Registering issue as requested [here](https://stackoverflow.com/questions/48944574/exchangelib-traversing-and-accessing-items-in-archive).

I'm trying to access my archived messages.

As expected, `print(account.root.tree())` returns:
```
root
├── AllItems
...
└── Øverst i informasjonslageret
    ├── Conversation Action Settings
    ├── Diskusjonslogg
    ├── Folders
    │   ├── ...
...
    ├── Innboks
...
```
However, `print(account.archive_msg_folder_root.tree())` returns:
`Øverst i informasjonslageret
` (Top of information store)

How can I access the tree structure and contained Items in the Archive?

**Comment by ecederstrand** [comment]
The two folders are either the same folder, or we're applying the wrong name to the distinguished folder `archive_msg_folder_root`. Can you print the folder IDs of the two folders?

```python
print((account.root / 'Øverst i informasjonslageret').folder_id)
print(account.archive_msg_folder_root.folder_id)
```

And also post the XML request and response when you call `account.archive_msg_folder_root` (see https://github.com/ecederstrand/exchangelib#troubleshooting)? I'd like to know what we're actually requesting, and the values that are returned when we request this distinguished folder.

**Comment by mcbuch** [comment]
Here's the code and output ():

`print((account.root / 'Øverst i informasjonslageret').folder_id)`:

> AAMkAGM3NmZhZmUyLWE5NWEtNDkxMi05ZTEyLTJiY2U0NWY2MTc4OAAuAAAAAACfolxovjp3TKuYwF4qDxD1AQALdYuLuelISpDNkO0ZcJFhAAAAAAEIAAA=

`print(account.archive_msg_folder_root.folder_id)`

> AAMkAGNmOTlhZDI1LTIxYTQtNDBlNC04ZWZiLWZmMGU0ODcyNzA2NAAuAAAAAABYnn6qFq3CTJTiRRKmg3AIAQC/964Ql/YQSpW9SPQsyUjdAAAAAAEIAAA=

```
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

account.archive_msg_folder_root
```
returns:

> ArchiveMsgFolderRoot(<exchangelib.account.Account object at 0x000001A31F3F3780>, 'Øverst i informasjonslageret', 0, 0, 14, None, 'AAMkAGNmOTlhZDI1LTIxYTQtNDBlNC04ZWZiLWZmMGU0ODcyNzA2NAAuAAAAAABYnn6qFq3CTJTiRRKmg3AIAQC/964Ql/YQSpW9SPQsyUjdAAAAAAEIAAA=', 'AQAAABYAAAC/964Ql/YQSpW9SPQsyUjdAAEdLFuj')

**Comment by mcbuch** [comment]
I'm feeling like a bit of an idiot, here. I suspect that I'm missing something elemental, but I cannot for the life of me figure out how to access the messages in the inbox and other folders in the archive. 

Here's a few test printouts. 

```
print(account.archive_root.total_count)
> 1
print(account.archive_deleted_items.total_count)
> 3779
print(account.archive_inbox.total_count)
> 0
print(account.archive_msg_folder_root.total_count)
> 0

print(account.archive_root.child_folder_count)
> 30
print(account.archive_deleted_items.child_folder_count)
> 0
print(account.archive_inbox.child_folder_count)
> 0
print(account.archive_msg_folder_root.child_folder_count)
> 14

print(account.archive_root.unread_count)
> 0
print(account.archive_deleted_items.unread_count)
> 1819
print(account.archive_inbox.unread_count)
> 0
print(account.archive_msg_folder_root.unread_count)
> 0

print(account.archive_root.name)
> archiveroot
print(account.archive_deleted_items.name)
> Slettede elementer
print(account.archive_inbox.name)
> Innboks
print(account.archive_msg_folder_root.name)
> Øverst i informasjonslaget
```
So I'm obviously accessing the archive, the number of unread in archive_deleted_items is indeed 1819. And
```
for item in account.archive_deleted_items.all()[:10]:
    print(item.subject)
```
... does indeed print out the subject of 10 deleted messages.

What am I missing? Why is the archive_inbox.total_count not returning the actual number of e-mails there? Could there be any restrictions server-side?

**Comment by mcbuch** [comment]
... Or could it be a language-issue?

**Comment by mcbuch** [comment]
I have now tested the problem on other e-mail accounts (within the same domain), with the same result.

**Comment by mcbuch** [comment]
Yet another test:
`print(account.archive_msg_folder_root.child_folder_count)` 
... returns 14.

```
for f in account.archive_msg_folder_root.walk():
    print(f)
``` 
... returns nothing.

**Comment by SteveTapajna** [comment]
I was seeing the same thing yesterday, and getting frustrated.  I could add folders under the archive and inbox, but I couldn't seen to find them when 'walking'.  Anyone else have a solution?

**Comment by ecederstrand** [comment]
Hi @mcbuch and @SteveTapajna I just committed a possible fix in https://github.com/ecederstrand/exchangelib/commit/71def9d94220eb639241b6a56a164cf4b7b9b593. Can you test that out?

**Comment by ecederstrand** [comment]
I assume this is fixed by https://github.com/ecederstrand/exchangelib/commit/71def9d94220eb639241b6a56a164cf4b7b9b593. Feel free to reopen if that's not the case.

**Comment by mcbuch** [comment]
Hi @ecederstrand , and sorry for not getting back to you sooner. 

I've tried upgrading with the fix, but the issue is still the same.
