### ISSUE TITLE
Getting Schema Validation error when access attachments

### ISSUE THREAD

**Issue by soaponarope** [ecederstrand/exchangelib#58]
Hi,

I had the following code which was previously working but is having issues since I upgraded to the newest versions:

        ap_folder = account.root.get_folder_by_name('auto-ap')
        for item in ap_folder.filter(is_read=False):
            print(item.subject)
            for attachment in item.attachments:
                if '\\' in attachment.name:
                    file_name = attachment.name.split('\\')[-1]
                else:
                    file_name = attachment.name
                file_path = os.path.join(config.INCOMING_DIR, cred['folder'], str(randrange(1, 999999)) + file_name)
                if os.path.isfile(file_path):
                    file_path = os.path.join(config.INCOMING_DIR, cred['folder'], str(randrange(1, 999999)) + file_name)
                print(attachment.name)
                if attachment.content is not None:
                    with open(file_path, 'wb') as f:
                        f.write(attachment.content)
                    file_count += 1
            item.is_read = True
            item.save()
            mail_count += 1

This is the full traceback:

> Traceback (most recent call last):
  File "C:/Dropbox/Projects/AutoAP/downloader.py", line 57, in <module>
    main()
  File "C:/Dropbox/Projects/AutoAP/downloader.py", line 45, in main
    if attachment.content is not None:
  File "C:\Python34\lib\site-packages\exchangelib\folders.py", line 1878, in content
    items=[self.attachment_id], include_mime_content=False))
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 918, in call
    return super(GetAttachment, self).call(**kwargs)
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 64, in call
    return self._get_elements(payload=self._get_payload(**kwargs))
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 75, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 128, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 156, in _get_soap_payload
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError
  File "C:\Python34\lib\site-packages\exchangelib\services.py", line 177, in _raise_soap_errors
    raise vars(errors)\[code\](msg)
exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.

**Comment by ecederstrand** [comment]
Can you add `DEBUG` logging and post the request and response data that triggered this? Thanks.

**Comment by soaponarope** [comment]
[debug.txt](https://github.com/ecederstrand/exchangelib/files/694097/debug.txt)

I've attached the console output with logging set to DEBUG.  Let me know if this isn't what you were asking for. Thank you!

**Comment by ecederstrand** [comment]
https://github.com/ecederstrand/exchangelib/commit/067804a9aea53619775b61cee2f46e1805fea576 should fix this for you

**Comment by soaponarope** [comment]
I am still getting an exception. I've attached the console output after I upgraded to the newest version of the master branch.

[new_debug.txt](https://github.com/ecederstrand/exchangelib/files/697309/new_debug.txt)

**Comment by ecederstrand** [comment]
Hmmm. Somehow, this is not triggered by the test suite. At least it's a new error this time. Try https://github.com/ecederstrand/exchangelib/commit/523fee221dbc248f0494cb4a409b9d204c9d854c

**Comment by soaponarope** [comment]
Works like a charm. Thanks!
