### ISSUE TITLE
ImportError: cannot import name 'DELEGATE'

### ISSUE THREAD

**Issue by WillBishop** [ecederstrand/exchangelib#72]
Not sure why this is happening, it worked in terminal, but now it doesn't work anywhere.

```from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, Mailbox, Attendee, Q```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 69, in <module>
    import email.parser
  File "/Users/Will/Desktop/email.py", line 1, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
ImportError: cannot import name 'DELEGATE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Will/Desktop/anythingbutemailreally.py", line 1, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, Mailbox, Attendee, Q
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/exchangelib/__init__.py", line 2, in <module>
    from .account import Account  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/exchangelib/account.py", line 12, in <module>
    from .autodiscover import discover
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/exchangelib/autodiscover.py", line 21, in <module>
    import requests.exceptions
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 69, in <module>
    import email.parser
  File "/Users/Will/Desktop/email.py", line 1, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
ImportError: cannot import name 'DELEGATE'
```

**Comment by WillBishop** [comment]
Fixed, don't have a file in the same directory as your script named `email.py`

**Comment by intobs** [comment]
Hello!
I updated your module to the latest version but error is still remained...
Run the example from the page https://github.com/ecederstrand/exchangelib

C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\python.exe C:/Users/burtsev_yv/Documents/DEV/bot/tests/email.py
Traceback (most recent call last):
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    from . import urllib3
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\burtsev_yv\Documents\DEV\bot\tests\email.py", line 7, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Q
ImportError: cannot import name 'DELEGATE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/burtsev_yv/Documents/DEV/bot/tests/email.py", line 7, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Q
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\__init__.py", line 2, in <module>
    from .account import Account  # noqa
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\account.py", line 12, in <module>
    from .autodiscover import discover
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 22, in <module>
    import requests.exceptions
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:\Users\burtsev_yv\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\burtsev_yv\Documents\DEV\bot\tests\email.py", line 7, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Q
ImportError: cannot import name 'DELEGATE'

**Comment by ecederstrand** [comment]
You also have a file called `email.py` in `C:\Users\burtsev_yv\Documents\DEV\bot\tests`. Don't do that because it shadows the `email` package from Python stdlib.
